version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network


networks:
  node-network:
    driver: bridge

