version: '3'

services:
  laravel: 
    #image: vitorrubio/laravelfc:prod
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    container_name: laravel
    networks:
      - laranet
  
  nginx: 
    #image: vitorrubio/nginxfc:prod
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod    
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge

