FROM php:7.4-cli

WORKDIR /var/www

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install libzip-dev -y && \
    apt install zip unzip -y && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '906a84df04cea2aa72f40b5f787e49f22d4c2f19492ac310e8cba5b96ac8b64115ac402c8cd292b8a03482574915d1a8') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    docker-php-ext-install zip && \
    mv composer.phar /usr/local/bin/composer && \
    composer create-project laravel/laravel laravel-app

EXPOSE 8000

ENTRYPOINT [ "php", "laravel-app/artisan", "serve" ]